build:
    image: staticfloat/binarybuilder.jl:v0.6-master
    variables:
        CI_REPO_OWNER: staticfloat
        CI_REPO_NAME: GlibcBuilder
    script:
        # build _all_ the versions!
        - for v in v2.12.2 v2.17 v2.19 v2.25 v2.27; do
              julia --color=yes build_tarballs.jl --glibc-version ${v};
          done
        # On tagged releases, upload our releases to github releases 
        - if [[ -n "${CI_COMMIT_TAG}" ]]; then
              ghr --username ${CI_REPO_OWNER} --repository ${CI_REPO_NAME} --replace ${CI_COMMIT_TAG} products/;
          fi
